### ISSUE TITLE
Python process gets killed everytime on running process_embeddings.py

### ISSUE THREAD

**Issue by warynice** [yanghoonkim/question_generation#2]
I tried running the code as directed on my local system as well as on Google Colab. Each time the "Reading Glove..." and "Processing Glove..." lines get printed and then after varying amounts of time, I get the response "killed". Maybe the Glove or the Vocab file is too large for the systems to handle.

**Comment by yanghoonkim** [comment]
Hi,

I actually checked the code right after updating to github if it works fine with instruction or not.

It may require the system to have memory of certain size, and it's not strange that processing glove cost some minutes.

What is the memory size of your system?

**Comment by warynice** [comment]
I have an 8GB RAM on my system.

Google Colab gives 12GB of RAM on paper, however, due to the shared environment, I assume the actual free compute is less, as is the case with its GPU.

How much of memory size will be optimum for this?

**Comment by yanghoonkim** [comment]
As I ran the code with the default setting, I found that the memory usage grew from 19702mb to 45951mb(approximately maximum value). I you don't have enough memory, you may try to split the glove file and modify the `process_embedding.py` code.

**Comment by warynice** [comment]
It ran without any hassle on a system with 32GB memory. Thanks a lot.
