### ISSUE TITLE
Hi, have u got the same result as Xinya?

### ISSUE THREAD

**Issue by cz3344** [yanghoonkim/question_generation#3]
Hi, have u got the same result as Xinya?

**Comment by yanghoonkim** [comment]
Till now, my code only contains sentence-level question generation model,  which is just a simple encoder-decoder with attention. However, it doesn't include the mechanism to remove UNK token, which is written in the paper. I remember that it doesn't have the same result as Xinya if I conducting experiment with the hyperparameter settings provided in the paper. But you can get the similar result if you well organize the settings.

**Comment by cz3344** [comment]
How abt now? Have you include the mechanism to remove UNK token? I saw you in another repo. lol

**Comment by yanghoonkim** [comment]
I was working on my neural question generation paper. I don't have exact plan to update the code. The code of my NQG paper is also on my github.
