### ISSUE TITLE
Implementing Glove Embedding

### ISSUE THREAD

**Issue by vvrmahendra** [yanghoonkim/question_generation#8]
While implementing Glove embedding, I ended up with following obstacles:-
Do, we need to change model's architecture to implement **Pretrained GloVe embeddings**? 
And what is the input shape for each LSTM node?
And during testing time is that easy to get back to word from a embedded vector? (What if we end up getting a vector which has no word to decode)

Help is much appreciated and Thanks in advance

**Comment by yanghoonkim** [comment]
What do you mean by implement pretrained GloVe embeddings? If you follow the **Usage** in README.md, you will get to use the pretrained GloVe embeddings actually.

input shape for the lstm node is the embedding_size which is defined in params.py

Available amount of vocabulary is already specified in voca_size in params.py, all those words that are not included by the vocabulary will be input/output as UNK token.

**Comment by vvrmahendra** [comment]
In the USAGE portion it's just downloaded, processed files and saved in DIC.NPY files. But I don't see it implemented in both training and testing. Only **Randomly initialized embeddings** is implemented. And the embedding size of both Random and Glove are different. So that's is the reason I asked **do we need to change model's architecture**... 

And my last question is not converting text to embedding vectors, my question is converting a vector(which is not in the list of embedding vectors) to word.

**Comment by yanghoonkim** [comment]
The code is actually using the processed glove embedding. Please pay attention to the **pre_embedding** parameter in params.py

About your last question, I think you have some misunderstanding about output layer in seq2seq model.

**Comment by vvrmahendra** [comment]
yeah @yanghoonkim ,  thank you very much... I am looking into that, I am able to figure it out.
